Repository Pylons-tech/pylons, pull requests merged in 2022-12, with the labels that each got.

#1499 block time reduced in upgrade.sh
  scripts/upgrade.sh
Labels: [zube]: In Progress

#1502 Redesigned the way we are getting the recipes and the items
  wallet/lib/ipc/handler/handlers/create_recipe_handler.dart
  wallet/lib/ipc/handler/handlers/create_stripe_account_handler.dart
  wallet/lib/ipc/ipc_engine.dart
  wallet/lib/main_prod.dart
  wallet/lib/pages/gestures_for_detail_screen.dart
  wallet/lib/pages/home/collection_screen/collection_screen.dart
  wallet/lib/pages/home/collection_screen/collection_view_model.dart
  wallet/lib/pages/home/home.dart
  wallet/lib/pages/home/home_provider.dart
  wallet/lib/pages/home/message_screen/message_screen.dart
  wallet/lib/pages/home/wallet_screen/wallet_screen.dart
  wallet/lib/pages/home/wallet_screen/widgets/latest_transactions.dart
  wallet/lib/pages/home/wallet_screen/widgets/row_components.dart
  wallet/lib/pages/owner_purchase_view_common/qr_code_screen.dart
  wallet/lib/pages/presenting_onboard_page/components/new_user_form.dart
  wallet/lib/pages/purchase_item/widgets/pay_now_dialog.dart
  wallet/lib/pages/routing_page/splash_screen.dart
  wallet/lib/pages/routing_page/update_app.dart
  wallet/lib/pages/settings/screens/general_screen/general_screen.dart
  wallet/lib/pages/settings/screens/general_screen/screens/payment_screen/screens/transaction_history.dart
  wallet/lib/pages/settings/screens/recovery_screen/screens/view_recovery_phrase.dart
  wallet/lib/pages/settings/screens/submit_feedback.dart
  wallet/lib/pages/settings/settings_screen.dart
  wallet/lib/providers/account_provider.dart
  wallet/lib/providers/collections_tab_provider.dart
  wallet/lib/providers/items_provider.dart
  wallet/lib/providers/recipes_provider.dart
  wallet/lib/pylons_app.dart
  wallet/lib/services/third_party_services/stripe_handler.dart
  wallet/lib/stores/wallet_store_imp.dart
  wallet/lib/utils/dependency_injection/dependency_injection.dart
  wallet/test/unit_testing/stores/wallet_store_imp_test.dart
  wallet/test/widget_testing/pages/routing_page/splash_screen_test.dart
Labels: [zube]: In Progress

#1500 updated upgrade Name
  app/upgrades/v5/constants.go
Labels: [zube]: In Review

#1521 (testapp) Bugfixes in advance of Monday
  testapp-flutter/.dart_tool/package_config.json
  testapp-flutter/android/app/src/main/AndroidManifest.xml
  testapp-flutter/assets/icon.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  testapp-flutter/lib/main.dart
  testapp-flutter/pubspec.lock
  testapp-flutter/pubspec.yaml
  testapp-flutter/recipe/README.md
  testapp-flutter/recipe/_cookbook.plc
  testapp-flutter/recipe/buy_sword.plr
  testapp-flutter/recipe/fight_dragon_armed.plr
  testapp-flutter/recipe/fight_dragon_unarmed.plr
  testapp-flutter/recipe/fight_goblin.plr
  testapp-flutter/recipe/fight_troll_armed.plr
  testapp-flutter/recipe/fight_troll_unarmed.plr
  testapp-flutter/recipe/get_character.plr
  testapp-flutter/recipe/pylons.gadgets
  testapp-flutter/recipe/randomness_demo.plr
  testapp-flutter/recipe/rest_100.plr
  testapp-flutter/recipe/rest_100_premium.plr
  testapp-flutter/recipe/rest_25.plr
  testapp-flutter/recipe/rest_50.plr
  testapp-flutter/recipe/rest_stopgap.plr
  testapp-flutter/recipe/upgrade_sword.plr
Labels: [zube]: In Progress

#1512 (testapp) Structure sword stuff better in the ui + warn when battles will 100% kill you.
  testapp-flutter/lib/main.dart
Labels: [zube]: In Progress

#1515 (testapp) Implement new icon
  testapp-flutter/.dart_tool/package_config.json
  testapp-flutter/android/app/src/main/AndroidManifest.xml
  testapp-flutter/assets/icon.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  testapp-flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  testapp-flutter/pubspec.lock
  testapp-flutter/pubspec.yaml
Labels: [zube]: In Progress

#1523 updated proposal
  app/upgrades/v5/constants.go
Labels: [zube]: In Progress

#1527 flutter proto was updated
  proto/buf.lock
  wallet/analysis_options.yaml
  wallet/android/app/build.gradle
  wallet/android/build.gradle
  wallet/android/gradle.properties
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/accounts.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/accounts.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/accounts.pbjson.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/apple_in_app_purchase_order.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/apple_in_app_purchase_order.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/cookbook.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/cookbook.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/event.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/event.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/event.pbjson.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/execution.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/execution.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/genesis.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/genesis.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/google_iap_order.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/google_iap_order.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/history.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/history.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/item.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/item.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/item.pbjson.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/jwk.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/jwk.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/params.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/params.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/payment_info.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/payment_info.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/query.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/query.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/recipe.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/recipe.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/redeem_info.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/redeem_info.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/standard_error.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/standard_error.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/stripe_refund.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/stripe_refund.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/trade.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/trade.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/tx.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/tx.pbenum.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/tx.pbgrpc.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/tx.pbjson.dart
  wallet/lib/services/data_stores/remote_data_store.dart
  wallet/lib/services/repository/repository.dart
  wallet/lib/stores/wallet_store_imp.dart
  wallet/pubspec.yaml
  wallet/test/mocks/mock_repository.dart
  x/pylons/types/item.pb.go
Labels: [zube]: In Progress

#1418 Remove BG below layer and smoother animation
  wallet/lib/pages/routing_page/splash_screen.dart
  wallet/lib/utils/image_util.dart
Labels: [zube]: In Progress

#1558 Updated chain id
  networks/pylons-mainnet-1/README.md
Labels: [zube]: In Progress

#1559 Nodes.Guru gentx
  networks/pylons-mainnet-1/gentx/NodesGuru.json
Labels: [zube]: In Progress

#1561 version fix.
  networks/pylons-mainnet-1/README.md
Labels: [zube]: In Progress

#1569 gentx with ubedrock
  networks/pylons-mainnet-1/README.md
Labels: [zube]: In Progress

#1581 Fix/mainnet mobile issues
  wallet/android/app/src/main/AndroidManifest.xml
  wallet/ios/Podfile
  wallet/ios/Runner.xcodeproj/project.pbxproj
  wallet/lib/pages/home/collection_screen/collection_screen.dart
  wallet/lib/pages/home/wallet_screen/widgets/latest_transactions.dart
  wallet/lib/pages/stripe_screen.dart
  wallet/lib/providers/items_provider.dart
  wallet/lib/providers/recipes_provider.dart
  wallet/macos/Flutter/GeneratedPluginRegistrant.swift
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/audio_session
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/biometric_storage
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/cloud_firestore
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/firebase_analytics
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/firebase_app_check
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/firebase_core
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/firebase_crashlytics
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/firebase_messaging
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/firebase_remote_config
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/flutter_local_notifications
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/flutter_secure_storage_macos
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/icloud_storage
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/just_audio
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/package_info
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/path_provider_macos
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/share_plus
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/shared_preferences_macos
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/sqflite
  wallet/macos/Flutter/ephemeral/.symlinks/plugins/url_launcher_macos
  wallet/macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  wallet/macos/Flutter/ephemeral/FlutterMacOS.podspec
  wallet/macos/Flutter/ephemeral/flutter_export_environment.sh
  wallet/macos/Podfile
  wallet/pubspec.yaml
Labels: [zube]: In Progress

#1565 Update mainnet README.md
  networks/pylons-mainnet-1/README.md
Labels: [zube]: In Progress

#1582 updated readme
  networks/pylons-mainnet-1/README.md
Labels: [zube]: In Progress

#1583 match shas and more rock
  networks/pylons-mainnet-1/README.md
Labels: [zube]: In Progress

#1663 upgrade handler was renamed
  app/app.go
  app/upgrades/v6/constants.go
  app/upgrades/v6/upgrades.go
  networks/pylons-mainnet-1/README.md
Labels: [zube]: In Progress

#1666 Huginn gentx
  networks/pylons-mainnet-1/gentx/Huginn.json
Labels: [zube]: In Progress

#1665 add_panxinyang_gentx
  networks/pylons-mainnet-1/gentx/gentx-panxinyang.json
Labels: [zube]: In Progress

#1659 Create Boris-gentx.json
  networks/pylons-mainnet-1/gentx/Boris-gentx.json
Labels: [zube]: In Progress

#1658 gentx_Rich_invest
  gentx_Rich_invest.json
Labels: [zube]: In Progress

#1656 Add AnyValid gentx
  networks/pylons-mainnet-1/gentx/AnyValid-gentx.json
Labels: [zube]: In Progress

#1655 Add MZONDER gentx
  networks/pylons-mainnet-1/gentx/gentx-c8f2d024f349eeb61993e482b61c598791d7d77e.json
Labels: [zube]: In Progress

#1653 Add silent gentx
  networks/pylons-mainnet-1/gentx/silent-gentx.json
Labels: [zube]: In Progress

#1649 Nodejumper gentx
  networks/pylons-mainnet-1/gentx/gentx-nodejumper.json
Labels: [zube]: In Progress

#1647 Create MCB.json
  networks/pylons-mainnet-1/gentx/MCB.json
Labels: [zube]: In Progress

#1646 Create bitszn-gentx.json
  networks/pylons-mainnet-1/gentx/bitszn-gentx.json
Labels: [zube]: In Progress

#1644 Pro-Nodes | SW33 gentx
  networks/pylons-mainnet-1/gentx/gentx-e2efbfd3b089181ae10ed50510dd521afd377a9e.json
Labels: [zube]: In Progress

#1641 add serfeklino gentx
  networks/pylons-mainnet-1/gentx/serfeklino.json
Labels: [zube]: In Progress

#1640 Add alenkaboom GenTX
  networks/pylons-mainnet-1/gentx/alenkaboom.json
Labels: [zube]: In Progress

#1638 add absnode gentx
  networks/pylons-mainnet-1/gentx/absnode_gentx.json
Labels: [zube]: In Progress

#1571 Create openbitlab.json mainnet-1
  networks/pylons-mainnet-1/gentx/openbitlab.json
Labels: [zube]: In Progress

#1635 gentx-jayjay.json
  networks/pylons-mainnet-1/gentx/gentx-jayjay.json
Labels: [zube]: In Progress

#1634 Add vbloher gentx
  networks/pylons-mainnet-1/gentx/gentx-vbloher.json
Labels: [zube]: In Progress

#1633 Create n0ok[MC].json
  networks/pylons-mainnet-1/gentx/n0ok[MC].json
Labels: [zube]: In Progress

#1632 add punq gentx
  networks/pylons-mainnet-1/gentx/punq gentx.json
Labels: [zube]: In Progress

#1631 Gentx_PPNV_Service.json
  networks/pylons-mainnet-1/gentx/PPNV_Service.json
Labels: [zube]: In Progress

#1630 Add Vanlee gentx
  networks/pylons-mainnet-1/gentx/gentx-Vanlee.json
Labels: [zube]: In Progress

#1539 Testapp cleanup
  .gitignore
  dart_sdk/lib/src/pylons_wallet.dart
  dart_sdk/lib/src/types/item.dart
  testapp-flutter/.dart_tool/package_config.json
  testapp-flutter/.gitignore
  testapp-flutter/README.md
  testapp-flutter/lib/character.dart
  testapp-flutter/lib/game.dart
  testapp-flutter/lib/main.dart
  testapp-flutter/pubspec.yaml
Labels: [zube]: In Review

#1532 Added File extension on Chain (Easel & Wallet)
  easel/lib/easel_provider.dart
  easel/lib/models/nft.dart
  easel/lib/services/third_party_services/database.g.dart
  easel/lib/utils/constants.dart
  wallet/lib/model/nft.dart
  wallet/lib/pages/detailed_asset_view/widgets/tab_fields.dart
  wallet/lib/utils/constants.dart
  wallet/test/mocks/mock_constants.dart
  wallet/test/mocks/owner_view_view_model.mocks.dart
  wallet/test/unit_testing/pages/purchase_item/purchase_item_view_model_test.mocks.dart
  wallet/test/widget_testing/pages/owner_view_screen_test.dart
  wallet/test/widget_testing/pages/purchase_item/purchase_item_screen_test.dart
Labels: [zube]: In Review

#1628 Seaman1247 gentx
  Seaman1247.json
Labels: [zube]: In Progress

#1625 Add medium gentx
  networks/pylons-mainnet-1/gentx/medium.json
Labels: [zube]: In Progress

#1624 4sv gentx
  networks/pylons-mainnet-1/gentx/gentx-286364ca6686d9d5ac0af4dcb9fa5aa77939df8b.json
Labels: [zube]: In Progress

#1623 Create gentx-legion.json
  pylons-mainnet-1/gentx/gentx-legion.json
Labels: [zube]: In Progress

#1622 Add StingRay gentx
  networks/pylons-mainnet-1/gentx/StingRay.json
Labels: [zube]: In Progress

#1620 StakeAngle gentx
  networks/pylons-mainnet-1/gentx/StakeAngle.json
Labels: [zube]: In Progress

#1619 Qubelabs gentx
  networks/pylons-mainnet-1/gentx/gentx-0f606f3fa1290d86e514a22a2b6a96ef4b58c70d.json
Labels: [zube]: In Progress

#1618 kallen gentx
  kallen.json
Labels: [zube]: In Progress

#1617 Add wombat gentx
  networks/pylons-mainnet-1/gentx/gentx-wombat.json
Labels: [zube]: In Progress

#1614 add gentx
  networks/pylons-mainnet-1/gentx/dreamstaker-gentx.json
Labels: [zube]: In Progress

#1613 OranG3cluB's genTX
  networks/pylons-mainnet-1/gentx/gentx-OranG3cluB.json
Labels: [zube]: In Progress

#1611 Shoni gentx
  Shoni gentx.json
Labels: [zube]: In Progress

#1667 Add kaygal gentx
  networks/pylons-mainnet-1/gentx/kaygal.json
Labels: [zube]: In Progress

#1660 Create gentx-levedevaekm.json
  networks/pylons-mainnet-1/gentx/gentx-levedevaekm.json
Labels: [zube]: In Progress

#1609 Add MTnode gentx
  networks/pylons-mainnet-1/gentx/gentx-MTnode.json
Labels: [zube]: In Progress

#1608 NullId gentx upload
  networks/pylons-mainnet-1/gentx/gentx-NullID.json
Labels: [zube]: In Progress

#1607 Create Gentx NodeStake.json
  networks/pylons-mainnet-1/gentx/NodeStake.json
Labels: [zube]: In Progress

#1605 TAKESHI gentx.json
  networks/pylons-mainnet-1/gentx/TAKESHI gentx.json
Labels: [zube]: In Progress

#1604 Add bdn gentx
  networks/pylons-mainnet-1/gentx/gentx-BDN.json
Labels: [zube]: In Progress

#1603 Add SerGo gentx
  networks/pylons-mainnet-1/gentx/SerGo.json
Labels: [zube]: In Progress

#1602 Gentx by STAVR
  networks/pylons-mainnet-1/gentx/STAVR.json
Labels: [zube]: In Progress

#1601 azstake gentx
  networks/pylons-mainnet-1/gentx/gentx-azstake.json
Labels: [zube]: In Progress

#1598 NG gentx fix $ROCK amount
  networks/pylons-mainnet-1/gentx/NodesGuru.json
Labels: [zube]: In Progress

#1597 Add Army IDs Gentx
  networks/pylons-mainnet-1/gentx/Army_IDs.json
Labels: [zube]: In Progress

#1596 Create oxes.json
  networks/pylons-mainnet-1/gentx/Add oxes.json
Labels: [zube]: In Progress

#1590 Add gentx Validator.run
  networks/pylons-mainnet-1/gentx/gentx-ValidatorRun.json
Labels: [zube]: In Progress

#1589 Create MMS-gentx.json
  networks/pylons-mainnet-1/gentx/MMS-gentx.json
Labels: [zube]: In Progress

#1568 add KingSuper gentx
  networks/pylons-mainnet-1/gentx/gentx-574a9497ef09f0364a7623ca45d7a5a067f4bc40.json
Labels: [zube]: In Progress

#1643 add stakingcabin gentx
  networks/pylons-mainnet-1/gentx/gentx-ffc593d3a670ed7b12a00f0e65d85b99654a0ae8.json
Labels: [zube]: In Progress

#1586 Create LavenderFive-gentx.json
  networks/pylons-mainnet-1/gentx/LavenderFive-gentx.json
Labels: [zube]: In Progress

#1636 cyberG gentx
  networks/pylons-mainnet-1/gentx/cyberG.json
Labels: [zube]: In Progress

#1629 add cyberomanov gentx.
  networks/pylons-mainnet-1/gentx/cyberomanov.json
Labels: [zube]: In Progress

#1594 Stake-Take gentx
  networks/pylons-mainnet-1/gentx/Stake-Take.json
Labels: [zube]: In Progress

#1662 Add Tigoo GenTx
  networks/pylons-mainnet-1/gentx/gentx-Tigoo.json
Labels: [zube]: In Progress

#1599 Brightlystake gentx
  networks/pylons-mainnet-1/gentx/gentx-Brightlystake.json
Labels: [zube]: In Progress

#1664 Create Bazilik gentx
  networks/pylons-mainnet-1/gentx/gentx-Bazilik.json
Labels: [zube]: In Progress

#1592 Create Gentx-AlxVoy.json
  networks/pylons-mainnet-1/gentx/Gentx-AlxVoy.json
Labels: [zube]: In Progress

#1657 Create gentx-5063cebecfcc41e1b2f2201df9e3506569fa5fb0.json
  networks/pylons-mainnet-1/gentx/gentx-5063cebecfcc41e1b2f2201df9e3506569fa5fb0.json
Labels: [zube]: In Progress

#1616 BVS gentx
  BVS gentx
Labels: [zube]: In Progress

#1610 Add files via upload
  gentx-dimasik.json
Labels: [zube]: In Progress

#1668 add iurii2002 gentx
  networks/pylons-mainnet-1/gentx/gentx-iurii2002.json
Labels: [zube]: In Progress

#1637 Add web3validator GENTX
  networks/pylons-mainnet-1/gentx/web3validator.json
Labels: [zube]: In Progress

#1587 Yurbason gentx file
  networks/pylons-mainnet-1/gentx/gentx-Yurbason.json
Labels: [zube]: In Progress

#1570 Create SimplyStaking.json
  networks/pylons-mainnet-1/gentx/SimplyStaking.json
Labels: [zube]: In Progress

#1591 Add jabbey gentx
  networks/pylons-mainnet-1/gentx/jabbey.json
Labels: [zube]: In Progress

#1606 Create gentx BuilderNode.json
  networks/pylons-mainnet-1/gentx/BuilderNode.json
Labels: [zube]: In Progress

#1670 Create Enigma-gentx.json
  networks/pylons-mainnet-1/gentx/Enigma-gentx.json
Labels: [zube]: In Progress

#1681 linter fixed
  app/upgrades/v4/upgrades_test.go
  app/upgrades/v6/upgrades.go
  x/pylons/client/cli/query_list_trades_by_creator_test.go
  x/pylons/client/cli/tx_cookbook_test.go
  x/pylons/types/messages_account_test.go
Labels: [zube]: In Progress

#1695 genesislab gentx
  networks/pylons-mainnet-1/gentx/genesislab-gentx.json
Labels: [zube]: In Progress

#1697 persistent peers added
  networks/pylons-mainnet-1/README.md
  networks/pylons-mainnet-1/persistent_peers.txt
Labels: [zube]: In Progress

#1673 Improvement: Added the platform based abstraction for the dart sdk
  dart_sdk/lib/src/features/ipc/handlers/create_cookbook_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/create_recipe_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/execute_recipe_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_cookbooks_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_execution_by_id_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_execution_by_recipe_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_item_by_id_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_list_items_by_owner_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_profile_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_recipe_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_recipes_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_trades_handler.dart
  dart_sdk/lib/src/features/ipc/ipc_handler_factory.dart
  dart_sdk/lib/src/features/ipc/responseCompleters.dart
  dart_sdk/lib/src/pylons_wallet/pylons_wallet_impl.dart
  dart_sdk/lib/src/pylons_wallet/response_fetcher/response_fetch.dart
  dart_sdk/test/src/features/ipc/handlers/get_cookbook_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_execution_by_id_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_execution_by_recipe_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_item_by_id_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_items_by_owner_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_profile_hander_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_recipe_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_recipes_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_trades_handler_test.dart
  dart_sdk/test/src/features/ipc/ipc_handler_factory_test.dart
Labels: [zube]: In Progress

#1698 Add seed node to mainnet
  networks/pylons-mainnet-1/README.md
Labels: [zube]: In Progress

#1679 Added drawer in wallet
  wallet/assets/images/svg/cash_out.svg
  wallet/assets/images/svg/history.svg
  wallet/assets/images/svg/image_edit.svg
  wallet/assets/images/svg/lock.svg
  wallet/i18n/de.json
  wallet/i18n/en.json
  wallet/i18n/es.json
  wallet/i18n/id.json
  wallet/i18n/ja.json
  wallet/i18n/ko.json
  wallet/i18n/ru.json
  wallet/i18n/vi.json
  wallet/lib/generated/locale_keys.g.dart
  wallet/lib/ipc/widgets/sdk_approval_dialog.dart
  wallet/lib/pages/detailed_asset_view/owner_view.dart
  wallet/lib/pages/detailed_asset_view/widgets/owner_video_player_screen.dart
  wallet/lib/pages/home/home.dart
  wallet/lib/pages/home/widget/pylons_drawer.dart
  wallet/lib/pages/purchase_item/purchase_item_screen.dart
  wallet/lib/pages/purchase_item/widgets/purchase_video_player_screen.dart
  wallet/lib/pages/purchase_item/widgets/purchase_video_progress_widget.dart
  wallet/lib/utils/constants.dart
  wallet/lib/utils/read_more.dart
  wallet/lib/utils/svg_util.dart
  wallet/test/mocks/home_provider.mocks.dart
  wallet/test/mocks/ipc_engine.mocks.dart
  wallet/test/mocks/mock_constants.dart
  wallet/test/mocks/repository.mocks.dart
  wallet/test/mocks/user_banner_view_model.mocks.dart
  wallet/test/mocks/user_info_provider.mocks.dart
  wallet/test/mocks/wallet_store.mocks.dart
  wallet/test/unit_testing/pages/purchase_item/purchase_item_view_model_test.mocks.dart
  wallet/test/widget_testing/pages/home/home_page_test.dart
Labels: [zube]: In Progress

#1361 Added accept policy screen
  wallet/i18n/de.json
  wallet/i18n/en.json
  wallet/i18n/es.json
  wallet/i18n/id.json
  wallet/i18n/ja.json
  wallet/i18n/ko.json
  wallet/i18n/ru.json
  wallet/i18n/vi.json
  wallet/lib/components/buttons/pylons_get_started_button.dart
  wallet/lib/generated/locale_keys.g.dart
  wallet/lib/ipc/ipc_engine.dart
  wallet/lib/pages/detailed_asset_view/widgets/owner_audio_widget.dart
  wallet/lib/pages/detailed_asset_view/widgets/owner_video_progress_widget.dart
  wallet/lib/pages/home/message_screen/message_tile.dart
  wallet/lib/pages/home/wallet_screen/widgets/view_in_collection_button.dart
  wallet/lib/pages/presenting_onboard_page/components/import_from_google_form.dart
  wallet/lib/pages/presenting_onboard_page/components/new_user_form.dart
  wallet/lib/pages/presenting_onboard_page/screens/accept_policy_screen.dart
  wallet/lib/pages/presenting_onboard_page/viewmodel/accept_policy_viewmodel.dart
  wallet/lib/pages/purchase_item/purchase_item_screen.dart
  wallet/lib/pages/purchase_item/purchase_item_view_model.dart
  wallet/lib/pages/purchase_item/widgets/purchase_audio_widget.dart
  wallet/lib/pages/purchase_item/widgets/purchase_video_progress_widget.dart
  wallet/lib/pages/routing_page/splash_screen.dart
  wallet/lib/pages/settings/screens/general_screen/screens/payment_screen/widgets/transaction_card.dart
  wallet/lib/pylons_app.dart
  wallet/lib/services/data_stores/local_data_store.dart
  wallet/lib/services/repository/repository.dart
  wallet/lib/stores/wallet_store_imp.dart
  wallet/lib/utils/clipper_utils.dart
  wallet/lib/utils/constants.dart
  wallet/lib/utils/dependency_injection/dependency_injection.dart
  wallet/lib/utils/failure/failure.dart
  wallet/lib/utils/favorites_change_notifier.dart
  wallet/lib/utils/image_util.dart
  wallet/lib/utils/route_util.dart
  wallet/test/mocks/accept_policy_viewmodel.mocks.dart
  wallet/test/mocks/mock_local_data_source.dart
  wallet/test/mocks/mock_repository.dart
  wallet/test/unit_testing/pages/purchase_item/purchase_item_view_model_test.mocks.dart
  wallet/test/unit_testing/services/data_stores/local_data_store_test.dart
  wallet/test/unit_testing/services/repository/repository_test.dart
  wallet/test/widget_testing/components/buttons/nft_buy_button_test.dart
  wallet/test/widget_testing/pages/accept_policy/accept_policy_screen_test.dart
Labels: [zube]: PR Review

#1520 Redesign free drop button
  wallet/assets/images/icons/eye_bold.svg
  wallet/assets/images/icons/like_bold.png
  wallet/assets/images/svg/curved_corner_red_bg.svg
  wallet/i18n/de.json
  wallet/i18n/en.json
  wallet/i18n/es.json
  wallet/i18n/id.json
  wallet/i18n/ja.json
  wallet/i18n/ko.json
  wallet/i18n/ru.json
  wallet/i18n/vi.json
  wallet/lib/generated/locale_keys.g.dart
  wallet/lib/pages/detailed_asset_view/widgets/tab_fields.dart
  wallet/lib/pages/purchase_item/purchase_item_screen.dart
  wallet/lib/pages/purchase_item/widgets/buy_nft_button.dart
  wallet/lib/utils/constants.dart
  wallet/lib/utils/svg_util.dart
  wallet/test/unit_testing/pages/purchase_item/purchase_item_view_model_test.mocks.dart
  wallet/test/widget_testing/components/buttons/nft_buy_button_test.dart
Labels: [zube]: In Progress

#1708 randomness_demo recipe fixed
  .gitignore
  testapp-flutter/recipe/randomness_demo.plr
Labels: [zube]: In Progress

#1707 upgrade v7 added: burn bedrock token
  app/app.go
  app/upgrades/mainnet/v1/constant.go
  app/upgrades/mainnet/v1/upgrades.go
  app/upgrades/mainnet/v1/upgrage_test.go
  app/upgrades/testnet/v3/constants.go
  app/upgrades/testnet/v3/fork.go
  app/upgrades/testnet/v4/constants.go
  app/upgrades/testnet/v4/msg_restrict_ubedrock_ante.go
  app/upgrades/testnet/v4/msg_restrict_ubedrock_ante_test.go
  app/upgrades/testnet/v4/upgrades.go
  app/upgrades/testnet/v4/upgrades_test.go
  app/upgrades/testnet/v5/constants.go
  app/upgrades/testnet/v5/upgrades.go
  app/upgrades/testnet/v5/upgrades_test.go
  app/upgrades/testnet/v6/constants.go
  app/upgrades/testnet/v6/upgrades.go
Labels: [zube]: In Progress

#1711 cel variables fixed
  x/pylons/types/default_cel.go
  x/pylons/types/messages_recipe.go
  x/pylons/types/messages_recipe_test.go
  x/pylons/types/recipe.go
  x/pylons/types/recipe_test.go
Labels: [zube]: In Progress

#1712 Updated the User experience of the android app
  dart_sdk/example/ios/Flutter/AppFrameworkInfo.plist
  dart_sdk/example/ios/Podfile
  dart_sdk/example/ios/Podfile.lock
  dart_sdk/example/ios/Runner.xcodeproj/project.pbxproj
  dart_sdk/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  dart_sdk/example/ios/Runner/Info.plist
  dart_sdk/example/lib/main.dart
  dart_sdk/lib/src/features/ipc/base/ipc_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/create_cookbook_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/create_recipe_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/execute_recipe_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_cookbooks_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_execution_by_id_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_execution_by_recipe_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_item_by_id_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_list_items_by_owner_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_profile_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_recipe_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_recipes_handler.dart
  dart_sdk/lib/src/features/ipc/handlers/get_trades_handler.dart
  dart_sdk/lib/src/features/ipc/ipc_handler_factory.dart
  dart_sdk/lib/src/pylons_wallet.dart
  dart_sdk/lib/src/pylons_wallet/pylons_wallet_impl.dart
  dart_sdk/lib/src/pylons_wallet/response_fetcher/response_fetch.dart
  dart_sdk/pubspec.yaml
  dart_sdk/test/src/features/ipc/handlers/get_cookbook_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_execution_by_id_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_execution_by_recipe_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_item_by_id_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_items_by_owner_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_profile_hander_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_recipe_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_recipes_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_trades_handler_test.dart
  dart_sdk/test/src/features/ipc/ipc_handler_factory_test.dart
  easel/i18n/de.json
  easel/i18n/en-US.json
  easel/i18n/es.json
  easel/i18n/ru-RU.json
  wallet/lib/ipc/local_server.dart
  wallet/lib/pages/home/widget/pylons_drawer.dart
  wallet/lib/pages/routing_page/splash_screen.dart
  wallet/lib/pages/settings/utils/user_info_provider.dart
  wallet/lib/utils/dependency_injection/dependency_injection.dart
  wallet/pubspec.yaml
Labels: [zube]: In Progress

#1710 added bedrock distrubution
  app/app.go
  x/pylons/keeper/distribution.go
  x/pylons/keeper/distribution_test.go
  x/pylons/keeper/hooks.go
  x/pylons/keeper/hooks_test.go
  x/pylons/keeper/token_economics_test.go
  x/pylons/types/distribution.go
  x/pylons/types/expected_keepers.go
Labels: [zube]: In Progress

#1421 Flavors added
  wallet/lib/main_development.dart
  wallet/lib/services/data_stores/remote_data_store.dart
  wallet/lib/services/third_party_services/remote_config_service/remote_config_service.dart
  wallet/lib/utils/dependency_injection/dependency_injection.dart
Labels: [zube]: In Progress

#1725 Added the pylons loading animation
  dart_sdk/analysis_options.yaml
  dart_sdk/assets/loading.gif
  dart_sdk/example/lib/main.dart
  dart_sdk/lib/low_level.dart
  dart_sdk/lib/pylons_sdk.dart
  dart_sdk/lib/src/ui/pylons_loading_animation.dart
  dart_sdk/pubspec.yaml
Labels: [zube]: In Progress

#1514 2.) Upload (new audio icon) #1395
  easel/assets/images/svg/audio_file_icon.svg
  easel/assets/images/svg/full_screen_img_gridview.svg
  easel/i18n/de.json
  easel/i18n/en-US.json
  easel/i18n/es.json
  easel/i18n/ru-RU.json
  easel/lib/generated/locale_keys.g.dart
  easel/lib/models/nft_format.dart
  easel/lib/screens/choose_format_screen.dart
  easel/lib/screens/preview_screen.dart
  easel/lib/utils/constants.dart
  easel/lib/widgets/image_widget.dart
  easel/lib/widgets/loading_with_progress.dart
  easel/lib/widgets/publish_button.dart
  easel/test/screens/choose_format_screen_test.dart
  easel/test/screens/preview_screen_test.dart
Labels: [zube]: PR Review
