Repository Pylons-tech/pylons, pull requests merged in 2022-09, with the labels that each got.

#863 Resolved Item Ownership History issue and error translations in Wallet
  wallet/i18n/de.json
  wallet/i18n/en.json
  wallet/lib/model/nft_ownership_history.dart
  wallet/lib/pages/detailed_asset_view/owner_view_view_model.dart
  wallet/lib/pages/purchase_item/purchase_item_view_model.dart
  wallet/lib/services/data_stores/remote_data_store.dart
  wallet/lib/services/repository/repository.dart
  wallet/lib/utils/constants.dart
  wallet/test/mocks/mock_repository.dart
Labels: test, mobile

#1054 SDK will now return cookbook
  .github/workflows/flutter.yml
  dart_sdk/example/lib/main.dart
  dart_sdk/lib/pylons_sdk.dart
  dart_sdk/lib/src/features/ipc/handlers/create_cookbook_handler.dart
  dart_sdk/lib/src/features/ipc/ipc_handler_factory.dart
  dart_sdk/lib/src/features/models/sdk_ipc_response.dart
  dart_sdk/lib/src/pylons_wallet.dart
  dart_sdk/lib/src/pylons_wallet/pylons_wallet_impl.dart
  dart_sdk/test/mocks/mock_constants.dart
  dart_sdk/test/pylons_wallet/pylons_wallet_impl_test.dart
  dart_sdk/test/src/features/core/error/exception_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_item_by_id_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_items_by_owner_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_recipe_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_recipes_handler_test.dart
  dart_sdk/test/src/features/ipc/handlers/get_trades_handler_test.dart
  dart_sdk/test/src/features/validations/validate_recipe_test.dart
  easel/pubspec.yaml
  wallet/lib/ipc/models/sdk_ipc_response.dart
  wallet/lib/stores/wallet_store.dart
  wallet/lib/stores/wallet_store_dummy_inventory.dart
  wallet/lib/stores/wallet_store_imp.dart
  wallet/test/mocks/mock_wallet_store.dart
  wallet/test/widget_testing/ipc/handler/handlers/create_cook_book_handler_test.dart
Labels: [zube]: In Progress

#1072 Removed dots menu button from Easel
  easel/lib/screens/creator_hub/widgets/nfts_grid_view.dart
Labels: [zube]: In Progress

#1081 Issue/986
  big-dipper/imports/startup/server/index.js
Labels: [zube]: In Progress

#1090 Updated test and added get execution logic
  dart_sdk/example/lib/main.dart
  dart_sdk/lib/src/features/ipc/handlers/execute_recipe_handler.dart
  dart_sdk/lib/src/features/ipc/ipc_handler_factory.dart
  dart_sdk/lib/src/pylons_wallet.dart
  dart_sdk/lib/src/pylons_wallet/pylons_wallet_impl.dart
  dart_sdk/test/pylons_wallet/pylons_wallet_impl_test.dart
  wallet/lib/stores/wallet_store_imp.dart
Labels: [zube]: In Progress

#1078 Fix three d upload issue
  easel/lib/repository/repository.dart
  easel/lib/screens/creator_hub/widgets/drafts_more_bottomsheet.dart
  easel/lib/screens/creator_hub/widgets/nfts_grid_view.dart
  easel/lib/utils/constants.dart
  easel/test/extensions/size_extension.dart
  easel/test/mocks/mock_constants.dart
  easel/test/widget/grid_view_draft_list_test.dart
Labels: [zube]: In Progress

#1058 Issue/1055
  big-dipper-backend/imports/startup/server/index.js
  big-dipper-backend/public/img/buy_icon.png
  big-dipper/client/main.js
  big-dipper/imports/startup/server/index.js
  big-dipper/imports/ui/easel_buy/EaselBuy.jsx
  big-dipper/imports/ui/item_share/ItemShare.jsx
  big-dipper/public/img/buy_icon.png
Labels: [zube]: In Progress

#1096 add cli/tx_recipe_test
  x/pylons/client/cli/tx_recipe_test.go
Labels: [zube]: In Progress

#1094 Fixed Image view aspect ratio in Pylons
  wallet/lib/pages/detailed_asset_view/widgets/nft_image_asset.dart
Labels: [zube]: In Progress

#1085 Fixed deeplink creation issue on buyer's side
  wallet/lib/pages/purchase_item/purchase_item_screen.dart
  wallet/lib/pages/purchase_item/purchase_item_view_model.dart
Labels: [zube]: In Progress

#1128 FCM token hotfix in Pylons
  wallet/lib/services/data_stores/remote_data_store.dart
Labels: [zube]: In Progress

#1104 Added ecommerce log when a purchase nft is opened
  wallet/lib/ipc/ipc_engine.dart
  wallet/lib/pages/purchase_item/purchase_item_screen.dart
  wallet/lib/pages/purchase_item/purchase_item_view_model.dart
  wallet/lib/pylons_app.dart
  wallet/lib/services/data_stores/remote_data_store.dart
  wallet/lib/services/repository/repository.dart
  wallet/lib/services/third_party_services/analytics_helper.dart
  wallet/lib/utils/route_util.dart
  wallet/test/mocks/mock_analytics_helper.dart
  wallet/test/mocks/mock_repository.dart
Labels: [zube]: In Progress

#1083 Fixed Invalid direction to published tab in Easel
  easel/lib/screens/describe_screen.dart
  easel/lib/screens/price_screen.dart
  easel/lib/screens/publish_screen.dart
  easel/lib/services/third_party_services/database.g.dart
  easel/lib/services/third_party_services/video_player_helper.dart
  easel/lib/utils/constants.dart
  easel/lib/utils/file_utils_helper.dart
  easel/pubspec.yaml
  easel/test/extensions/size_extensions.dart
  easel/test/mock/media_info.mocks.dart
  easel/test/mock/mock_audio_imp.dart
  easel/test/mock/mock_constants.dart
  easel/test/mock/mock_file_utils.dart
  easel/test/mock/mock_repository.dart
  easel/test/mock/mock_video_player.dart
  easel/test/widget/save_as_draft_button_test.dart
Labels: [zube]: In Progress

#1139 Added kotlin dependencies
  easel/lib/repository/repository.dart
  easel/test/widget/grid_view_draft_list_test.dart
  wallet/.metadata
  wallet/android/app/build.gradle
  wallet/android/app/src/main/AndroidManifest.xml
  wallet/android/app/src/main/java/tech/pylons/wallet/MainActivity.java
  wallet/android/app/src/main/java/tech/pylons/wallet/Pigeon.java
  wallet/android/app/src/main/kotlin/tech/pylons/flutter_wallet/MainActivity.kt
  wallet/android/app/src/main/kotlin/tech/pylons/flutter_wallet/PylonsWidgetProvider.kt
  wallet/android/app/src/main/kotlin/tech/pylons/flutter_wallet/PylonsWidgetService.kt
  wallet/android/app/src/main/kotlin/tech/pylons/wallet/HomeWidgetExampleProvider.kt
  wallet/android/app/src/main/kotlin/tech/pylons/wallet/MainActivity.kt
  wallet/android/app/src/main/res/layout/example_layout.xml
  wallet/android/app/src/main/res/xml/home_widget_example.xml
  wallet/android/build.gradle
  wallet/pigeons/message.dart
  wallet/pubspec.yaml
Labels: [zube]: In Progress

#1132 Added analytics firebase
  easel/lib/main.dart
  easel/lib/services/third_party_services/analytics_helper.dart
  easel/lib/utils/dependency_injection/dependency_injection_container.dart
  easel/pubspec.yaml
Labels: [zube]: In Progress

#1103 Restore creater images to their original aspect ratio
  easel/lib/screens/preview_screen.dart
  easel/lib/widgets/image_widget.dart
  wallet/lib/pages/detailed_asset_view/widgets/nft_image_asset.dart
Labels: [zube]: In Progress

#1118 Fixed Buy Button removed issue in expanded detail view in Pylons
  wallet/lib/pages/purchase_item/purchase_item_screen.dart
  wallet/lib/utils/constants.dart
  wallet/test/mocks/mock_constants.dart
  wallet/test/widget_testing/components/buttons/nft_buy_button_test.dart
Labels: [zube]: In Progress

#1144 Fixed Buy Button for Free NFT
  wallet/i18n/de.json
  wallet/i18n/en.json
  wallet/i18n/es.json
  wallet/i18n/id.json
  wallet/i18n/ja.json
  wallet/i18n/ko.json
  wallet/i18n/ru.json
  wallet/i18n/vi.json
  wallet/lib/pages/purchase_item/purchase_item_screen.dart
  wallet/lib/pages/purchase_item/widgets/buy_nft_button.dart
  wallet/test/mocks/mock_constants.dart
  wallet/test/widget_testing/components/buttons/buy_nft_button_test.dart
  wallet/test/widget_testing/pages/gesture_for_detail_screen_test.dart
Labels: [zube]: In Progress

#1158 Fix network popup issue in Pylons
  wallet/lib/pages/routing_page/routing_page.dart
  wallet/lib/pylons_app.dart
  wallet/lib/services/third_party_services/network_info.dart
  wallet/lib/utils/dependency_injection/dependency_injection.dart
Labels: [zube]: In Progress

#808 Dang/add test spam mitigation
  app/ante_gate_test.go
  scripts/spam_mitigation.sh
  scripts/test_node_deploy.sh
  scripts/test_spam_mitigation.sh
Labels: bigdipper, chain, [zube]: To Do

#1167 Resolved the issue with easel build
  easel/android/app/build.gradle
  easel/ios/Runner.xcodeproj/project.pbxproj
  easel/pubspec.yaml
  wallet/ios/Runner.xcodeproj/project.pbxproj
  wallet/lib/pages/purchase_item/purchase_item_screen.dart
  wallet/lib/pages/purchase_item/purchase_item_view_model.dart
  wallet/pkgs/alan/pubspec.yaml
  wallet/pubspec.yaml
  wallet/test/unit_testing/pages/purchase_item/purchase_item_view_model_test.dart
  wallet/test/unit_testing/pages/purchase_item/purchase_item_view_model_test.mocks.dart
Labels: [zube]: In Progress

#1174 Remove/html
  big-dipper/imports/startup/server/index.js
Labels: [zube]: In Progress

#1170 Added borg library for ci
  .github/workflows/flutter.yml
  wallet/borg.sh
  wallet/lib/model/amount.dart
  wallet/pkgs/alan/pubspec.yaml
  wallet/pkgs/cosmos_utils/.gitignore
  wallet/pkgs/cosmos_utils/.metadata
  wallet/pkgs/cosmos_utils/CHANGELOG.md
  wallet/pkgs/cosmos_utils/LICENSE
  wallet/pkgs/cosmos_utils/README.md
  wallet/pkgs/cosmos_utils/lib/address_parser.dart
  wallet/pkgs/cosmos_utils/lib/amount_formatter.dart
  wallet/pkgs/cosmos_utils/lib/app_info_extractor.dart
  wallet/pkgs/cosmos_utils/lib/app_info_provider.dart
  wallet/pkgs/cosmos_utils/lib/colors_generator.dart
  wallet/pkgs/cosmos_utils/lib/cosmos_utils.dart
  wallet/pkgs/cosmos_utils/lib/credentials_storage_failure.dart
  wallet/pkgs/cosmos_utils/lib/data_store.dart
  wallet/pkgs/cosmos_utils/lib/extensions.dart
  wallet/pkgs/cosmos_utils/lib/future_either.dart
  wallet/pkgs/cosmos_utils/lib/group_by_extension.dart
  wallet/pkgs/cosmos_utils/lib/logger.dart
  wallet/pkgs/cosmos_utils/lib/mnemonic.dart
  wallet/pkgs/cosmos_utils/lib/not_implemented.dart
  wallet/pkgs/cosmos_utils/pubspec.yaml
  wallet/pkgs/pdf_viewer-master/pubspec.yaml
  wallet/pkgs/transaction_signing_gateway/pubspec.yaml
  wallet/pubspec.yaml
Labels: [zube]: In Progress

#1161 add cli/tx_transfer_cookbook_test
  x/pylons/client/cli/tx_transfer_cookbook_test.go
Labels: [zube]: In Progress

#1159 add cli/tx_trade_test
  x/pylons/client/cli/tx_trade_test.go
Labels: [zube]: In Progress

#1162 add cli/tx_cookbook_test.go
  x/pylons/client/cli/tx_cookbook_test.go
Labels: [zube]: In Progress
