Repository Pylons-tech/pylons, pull requests merged in 2022-11, with the labels that each got.

#1321 Update/localization keys
  docs/pylons-docs/content/pylonsd/page-2.md
  docs/pylons-docs/content/pylonsd/page-3.md
  docs/pylons-docs/content/pylonsd/page-4.md
  docs/pylons-docs/public/pylonsd/quick-start
  easel/.translations.sh
  easel/i18n/de.json
  easel/i18n/en-US.json
  easel/i18n/es.json
  easel/i18n/ru-RU.json
  easel/lib/easel_provider.dart
  easel/lib/generated/locale_keys.g.dart
  easel/lib/repository/repository.dart
  easel/lib/screens/choose_format_screen.dart
  easel/lib/screens/creator_hub/creator_hub_screen.dart
  easel/lib/screens/creator_hub/creator_hub_view_model.dart
  easel/lib/screens/creator_hub/widgets/delete_confirmation_dialog.dart
  easel/lib/screens/creator_hub/widgets/draft_list_tile.dart
  easel/lib/screens/creator_hub/widgets/drafts_more_bottomsheet.dart
  easel/lib/screens/creator_hub/widgets/nfts_list_tile.dart
  easel/lib/screens/creator_hub/widgets/published_nfts_bottom_sheet.dart
  easel/lib/screens/custom_widgets/initial_draft_detail_dialog.dart
  easel/lib/screens/custom_widgets/step_labels.dart
  easel/lib/screens/describe_screen.dart
  easel/lib/screens/preview_screen.dart
  easel/lib/screens/price_screen.dart
  easel/lib/screens/publish_screen.dart
  easel/lib/screens/splash_screen.dart
  easel/lib/screens/tutorial_screen.dart
  easel/lib/screens/welcome_easel.dart
  easel/lib/services/datasources/local_datasource.dart
  easel/lib/services/datasources/remote_datasource.dart
  easel/lib/utils/constants.dart
  easel/lib/utils/file_utils_helper.dart
  easel/lib/viewmodels/home_viewmodel.dart
  easel/lib/widgets/easel_price_input_field.dart
  easel/lib/widgets/pdf_viewer.dart
  easel/lib/widgets/publish_button.dart
  easel/lib/widgets/video_widget_full_screen.dart
Labels: [zube]: In Progress

#1338 Working branch cleanup
  dart_sdk/example/lib/main.dart
  dart_sdk/lib/low_level.dart
  dart_sdk/lib/src/types/recipe.dart
  dart_sdk/lib/src/types/trade.dart
  dart_sdk/test/mocks/mockedWallet.dart
  dart_sdk/test/src/features/ipc/handlers/get_trades_handler_test.dart
  easel/lib/easel_provider.dart
  easel/lib/models/nft.dart
  easel/lib/repository/repository.dart
  easel/lib/screens/creator_hub/creator_hub_view_model.dart
  easel/lib/services/datasources/remote_datasource.dart
  easel/lib/utils/extension_util.dart
  easel/test/mock/mock_repository.dart
  stubwallet/.gitignore
  stubwallet/.metadata
  stubwallet/README.md
  stubwallet/analysis_options.yaml
  stubwallet/lib/main.dart
  stubwallet/pubspec.lock
  stubwallet/pubspec.yaml
  stubwallet/test/widget_test.dart
  stubwallet/windows/.gitignore
  stubwallet/windows/CMakeLists.txt
  stubwallet/windows/flutter/CMakeLists.txt
  stubwallet/windows/flutter/generated_plugin_registrant.cc
  stubwallet/windows/flutter/generated_plugin_registrant.h
  stubwallet/windows/flutter/generated_plugins.cmake
  stubwallet/windows/runner/CMakeLists.txt
  stubwallet/windows/runner/Runner.rc
  stubwallet/windows/runner/flutter_window.cpp
  stubwallet/windows/runner/flutter_window.h
  stubwallet/windows/runner/main.cpp
  stubwallet/windows/runner/resource.h
  stubwallet/windows/runner/resources/app_icon.ico
  stubwallet/windows/runner/runner.exe.manifest
  stubwallet/windows/runner/utils.cpp
  stubwallet/windows/runner/utils.h
  stubwallet/windows/runner/win32_window.cpp
  stubwallet/windows/runner/win32_window.h
Labels: [zube]: In Progress

#1296 Adjusted Creator Hub Screen according to suggested changes.
  easel/assets/images/svg/file_type_image.svg
  easel/i18n/de.json
  easel/i18n/en-US.json
  easel/i18n/es.json
  easel/i18n/ru-RU.json
  easel/lib/screens/creator_hub/creator_hub_screen.dart
  easel/lib/screens/creator_hub/creator_hub_view_model.dart
  easel/lib/screens/creator_hub/widgets/draft_list_tile.dart
  easel/lib/screens/creator_hub/widgets/drafts_more_bottomsheet.dart
  easel/lib/screens/creator_hub/widgets/nfts_grid_view.dart
  easel/lib/screens/creator_hub/widgets/nfts_list_tile.dart
  easel/lib/screens/creator_hub/widgets/published_nfts_bottom_sheet.dart
  easel/lib/utils/constants.dart
  easel/test/mocks/mock_constants.dart
  easel/test/widget/draft_list_tile_test.dart
  easel/test/widget/grid_view_draft_list_test.dart
  easel/test/widget/gridview_banner_for_draft_published_test.dart
  easel/test/widget/nfts_list_tile_test.dart
Labels: mobile, Easel App, [zube]: In Progress

#1336 Fix Firebase AppCheck issue
  wallet/android/app/build.gradle
  wallet/android/app/src/main/kotlin/tech/pylons/wallet/MainActivity.kt
  wallet/ios/Podfile
  wallet/ios/Runner/AppDelegate.swift
  wallet/lib/main_prod.dart
  wallet/lib/utils/constants.dart
Labels: [zube]: In Progress

#1272 Feat/nft wallpaper
  wallet/android/app/src/main/AndroidManifest.xml
  wallet/android/app/src/main/res/xml/file_paths.xml
  wallet/i18n/de.json
  wallet/i18n/en.json
  wallet/i18n/es.json
  wallet/i18n/id.json
  wallet/i18n/ja.json
  wallet/i18n/ko.json
  wallet/i18n/ru.json
  wallet/i18n/vi.json
  wallet/lib/generated/locale_keys.g.dart
  wallet/lib/pages/detailed_asset_view/owner_view.dart
  wallet/lib/pages/detailed_asset_view/widgets/wallpaper_set_screen.dart
  wallet/lib/pages/transaction_failure_manager/local_transaction_detail_screen.dart
  wallet/lib/services/third_party_services/remote_notifications_service.dart
  wallet/pubspec.yaml
  wallet/test/widget_testing/components/wallpaper_set_screen_test.dart
Labels: [zube]: In Progress

#1362 Use DecString helpers instead of (incorrect) hardcoded conversion logic
  dart_sdk/lib/src/types/recipe.dart
Labels: [zube]: In Progress

#1283 NFT Listing Full Screen View (pylons app)
  wallet/i18n/de.json
  wallet/i18n/en.json
  wallet/i18n/es.json
  wallet/i18n/id.json
  wallet/i18n/ja.json
  wallet/i18n/ko.json
  wallet/i18n/ru.json
  wallet/i18n/vi.json
  wallet/lib/generated/locale_keys.g.dart
  wallet/lib/model/nft.dart
  wallet/lib/pages/detailed_asset_view/owner_view.dart
  wallet/lib/pages/detailed_asset_view/owner_view_view_model.dart
  wallet/lib/pages/detailed_asset_view/widgets/tab_fields.dart
  wallet/lib/pages/home/currency_screen/model/ibc_coins.dart
  wallet/lib/pages/purchase_item/purchase_item_screen.dart
  wallet/lib/pages/purchase_item/purchase_item_view_model.dart
  wallet/lib/pages/purchase_item/widgets/buy_nft_button.dart
  wallet/lib/utils/constants.dart
  wallet/lib/utils/read_more.dart
  wallet/pubspec.yaml
  wallet/test/mocks/mock_constants.dart
  wallet/test/mocks/mock_repository.dart
  wallet/test/mocks/purchase_item_view_model.mocks.dart
  wallet/test/unit_testing/pages/purchase_item/purchase_item_view_model_test.mocks.dart
  wallet/test/unit_testing/stores/wallet_store_imp_test.mocks.dart
  wallet/test/widget_testing/components/buttons/nft_buy_button_test.dart
Labels: [zube]: In Progress

#1373 Feat favourite
  wallet/lib/model/favorites.dart
  wallet/lib/model/transaction_failure_model.dart
  wallet/lib/services/data_stores/local_data_store.dart
  wallet/lib/services/third_party_services/database/dao/favorites_dao.dart
  wallet/lib/services/third_party_services/database/dao/tx_manager_dao.dart
  wallet/lib/services/third_party_services/database/database.dart
  wallet/lib/services/third_party_services/database/database.g.dart
  wallet/lib/utils/dependency_injection/dependency_injection.dart
  wallet/test/unit_testing/pages/purchase_item/purchase_item_view_model_test.mocks.dart
Labels: [zube]: In Progress

#1309 Faisal/upgrade handler
  app/app.go
  app/apptesting/test_suite.go
  app/test_helpers.go
  app/upgrade/const.go
  app/upgrades/types.go
  app/upgrades/v3/constants.go
  app/upgrades/v3/fork.go
  app/upgrades/v4/constants.go
  app/upgrades/v4/msg_restrict_ubedrock_ante.go
  app/upgrades/v4/msg_restrict_ubedrock_ante_test.go
  app/upgrades/v4/upgrades.go
  app/upgrades/v4/upgrades_test.go
  docs/ipfs.png
  docs/software-upgrade.md
  proto/pylons/pylons/accounts.proto
  proto/pylons/pylons/event.proto
  proto/pylons/pylons/tx.proto
  scripts/upgrade.sh
  x/pylons/handler.go
  x/pylons/keeper/keeper_test.go
  x/pylons/keeper/migrations.go
  x/pylons/keeper/msg_server_kyc_address.go
  x/pylons/keeper/pylons_account.go
  x/pylons/keeper/pylons_account_test.go
  x/pylons/migrations/v3/migration.go
  x/pylons/migrations/v4/migration.go
  x/pylons/module.go
  x/pylons/types/accounts.pb.go
  x/pylons/types/event.pb.go
  x/pylons/types/keys.go
  x/pylons/types/message_send_items.go
  x/pylons/types/messages_kyc_address.go
  x/pylons/types/tx.pb.go
  x/pylons/types/utils.go
Labels: [zube]: In Progress

#1347 Feat/maintenance mode
  wallet/.translations.sh
  wallet/i18n/de.json
  wallet/i18n/en.json
  wallet/i18n/es.json
  wallet/i18n/id.json
  wallet/i18n/ja.json
  wallet/i18n/ko.json
  wallet/i18n/ru.json
  wallet/i18n/vi.json
  wallet/lib/components/maintenance_mode_widgets.dart
  wallet/lib/generated/locale_keys.g.dart
  wallet/lib/pages/home/home.dart
  wallet/lib/services/third_party_services/remote_config_service/remote_config_service.dart
  wallet/test/mocks/maintenance_mode_widgets_test.mocks.dart
  wallet/test/unit_testing/pages/purchase_item/purchase_item_view_model_test.mocks.dart
  wallet/test/widget_testing/components/maintenance_mode_widgets_test.dart
Labels: [zube]: In Progress

#1378 fixed bedrock distrubution
  app/upgrades/v4/upgrades.go
Labels: [zube]: In Progress

#1381 fix: revert back bigdipper
  big-dipper/package-lock.json
  big-dipper/package.json
Labels: [zube]: In Progress

#1377 Updated lints in easel.
  easel/analysis_options.yaml
  easel/lib/easel_provider.dart
  easel/lib/models/denom.dart
  easel/lib/models/nft.dart
  easel/lib/models/nft_format.dart
  easel/lib/models/storage_response_model.dart
  easel/lib/repository/repository.dart
  easel/lib/screens/choose_format_screen.dart
  easel/lib/screens/creator_hub/creator_hub_screen.dart
  easel/lib/screens/creator_hub/creator_hub_view_model.dart
  easel/lib/screens/creator_hub/widgets/draft_list_tile.dart
  easel/lib/screens/creator_hub/widgets/drafts_more_bottomsheet.dart
  easel/lib/screens/creator_hub/widgets/nfts_list_tile.dart
  easel/lib/screens/creator_hub/widgets/published_nfts_bottom_sheet.dart
  easel/lib/screens/creator_hub/widgets/video_placeholder.dart
  easel/lib/screens/custom_widgets/initial_draft_detail_dialog.dart
  easel/lib/screens/custom_widgets/step_labels.dart
  easel/lib/screens/custom_widgets/steps_indicator.dart
  easel/lib/screens/describe_screen.dart
  easel/lib/screens/home_screen.dart
  easel/lib/screens/preview_nft/nft_video_player_screen.dart
  easel/lib/screens/preview_nft/preview_nft_full_screen.dart
  easel/lib/screens/preview_screen.dart
  easel/lib/screens/price_screen.dart
  easel/lib/screens/publish_screen.dart
  easel/lib/screens/splash_screen.dart
  easel/lib/screens/tutorial_screen.dart
  easel/lib/screens/welcome_easel.dart
  easel/lib/screens/welcome_screen/widgets/show_something_wrong_dialog.dart
  easel/lib/screens/welcome_screen/widgets/show_wallet_install_dialog.dart
  easel/lib/services/datasources/cache_manager.dart
  easel/lib/services/datasources/local_datasource.dart
  easel/lib/services/datasources/remote_datasource.dart
  easel/lib/services/third_party_services/video_player_helper.dart
  easel/lib/utils/amount_formatter.dart
  easel/lib/utils/extension_util.dart
  easel/lib/utils/file_utils_helper.dart
  easel/lib/utils/read_more.dart
  easel/lib/viewmodels/home_viewmodel.dart
  easel/lib/widgets/audio_widget.dart
  easel/lib/widgets/clippers/bottom_sheet_clipper.dart
  easel/lib/widgets/easel_hashtag_input_field.dart
  easel/lib/widgets/easel_price_input_field.dart
  easel/lib/widgets/easel_text_field.dart
  easel/lib/widgets/model_viewer.dart
  easel/lib/widgets/pdf_viewer_full_screen.dart
  easel/lib/widgets/pylons_button.dart
  easel/lib/widgets/rounded_purple_button_widget.dart
  easel/lib/widgets/video_widget.dart
  easel/lib/widgets/video_widget_full_screen.dart
  easel/pubspec.yaml
  easel/test/mock/mock_repository.dart
  easel/test/mocks/mock_constants.dart
  easel/test/models/denom_test.dart
  wallet/analysis_options.yaml
  wallet/pubspec.yaml
Labels: [zube]: In Progress

#1371 Added Splash Screen
  wallet/assets/images/icons/pylons_logo_dark.png
  wallet/assets/images/splash/Splash_Screen.jpg
  wallet/assets/images/splash/bg-1.png
  wallet/assets/images/splash/bg-2.png
  wallet/assets/images/splash/bg-3.png
  wallet/assets/images/splash/bg-4.png
  wallet/assets/images/splash/bg-5.png
  wallet/assets/images/splash/bg-6.png
  wallet/assets/images/svg/dummy_user.svg
  wallet/lib/pages/detailed_asset_view/widgets/wallpaper_set_screen.dart
  wallet/lib/pages/routing_page/routing_page.dart
  wallet/lib/pages/routing_page/splash_screen.dart
  wallet/lib/pylons_app.dart
  wallet/lib/utils/constants.dart
  wallet/lib/utils/image_util.dart
  wallet/pubspec.yaml
  wallet/test/widget_testing/pages/routing_page/splash_screen_test.dart
Labels: [zube]: In Progress

#1379 When User is in Creator Hub and is on the Published NFT- Publish Button Should NOT be an option and only have One Pop Screen to be Directed to Pylons or IPFS #1376
  easel/lib/screens/creator_hub/widgets/draft_list_tile.dart
  easel/lib/screens/creator_hub/widgets/nfts_grid_view.dart
  easel/lib/screens/creator_hub/widgets/nfts_list_tile.dart
  easel/lib/utils/constants.dart
  easel/test/mock/mock_constants.dart
  easel/test/widget/file_type_icon_test.dart
  easel/test/widget/gridview_banner_for_draft_published_test.dart
Labels: [zube]: In Progress

#1407 Fixed issue of continues loader in case of Apple IAP
  wallet/lib/pylons_app.dart
Labels: [zube]: In Progress

#1411 Enhance shadow below pylons images & added fade transition
  wallet/lib/pages/routing_page/splash_screen.dart
Labels: [zube]: In Progress

#1412 Fixed price banner for both list and grid view in Easel.
  easel/lib/screens/creator_hub/creator_hub_screen.dart
  easel/lib/screens/creator_hub/widgets/nfts_list_tile.dart
  easel/lib/utils/extension_util.dart
  easel/test/mocks/mock_constants.dart
  easel/test/widget/gridview_banner_for_draft_published_test.dart
  easel/test/widget/nfts_list_tile_test.dart
Labels: [zube]: In Progress

#1300 Update/documentation
  TECHNICAL-SETUP.md
  docs/TESTNET.md
  docs/pylons-docs/content/dev-tool/page-1.md
  docs/pylons-docs/content/pylonsd/page-1.md
  docs/pylons-docs/content/pylonsd/page-2.md
  docs/pylons-docs/content/pylonsd/page-3.md
  docs/pylons-docs/public/pylonsd/tech-setup
Labels: [zube]: In Progress

#1390 [feat] added bedrock distribution for master wallet
  app/app.go
  app/apptesting/test_suite.go
  app/upgrades/Readme.md
  app/upgrades/v4/upgrades_test.go
  app/upgrades/v5/constants.go
  app/upgrades/v5/upgrades.go
  app/upgrades/v5/upgrades_test.go
Labels: [zube]: In Progress

#1419 Only allowed potrait mode
  easel/ios/Runner.xcodeproj/project.pbxproj
  easel/ios/Runner/Info.plist
  easel/lib/main.dart
  easel/pubspec.yaml
  wallet/ios/Runner.xcodeproj/project.pbxproj
  wallet/ios/Runner/Info.plist
  wallet/lib/main_prod.dart
  wallet/pubspec.yaml
Labels: [zube]: In Progress

#1431 Remove safetyNet Provider
  wallet/lib/main_prod.dart
Labels: [zube]: In Review

#1428 Create user account without user name
  proto/buf.lock
  proto/pylons/pylons/item.proto
  proto/pylons/pylons/tx.proto
  testutil/cli/cli_test_util.go
  testutil/network/network.go
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/item.pb.dart
  wallet/lib/modules/Pylonstech.pylons.pylons/module/client/pylons/item.pbjson.dart
  x/pylons/client/cli/query_list_referrals_by_address_test.go
  x/pylons/client/cli/query_list_trades_by_creator_test.go
  x/pylons/client/cli/tx.go
  x/pylons/client/cli/tx_account.go
  x/pylons/client/cli/tx_account_test.go
  x/pylons/genesis.go
  x/pylons/handler.go
  x/pylons/keeper/complete_pending_execution.go
  x/pylons/keeper/complete_pending_execution_test.go
  x/pylons/keeper/execute_recipe_history.go
  x/pylons/keeper/grpc_query_list_referrals_by_address_test.go
  x/pylons/keeper/keeper_test.go
  x/pylons/keeper/msg_server_account.go
  x/pylons/keeper/msg_server_account_test.go
  x/pylons/keeper/msg_server_execute_recipe_test.go
  x/pylons/keeper/msg_server_fulfill_trade.go
  x/pylons/keeper/msg_server_send_items.go
  x/pylons/keeper/pylons_account.go
  x/pylons/simulation/operations.go
  x/pylons/types/errors.go
  x/pylons/types/item.go
  x/pylons/types/item.pb.go
  x/pylons/types/messages_account.go
  x/pylons/types/messages_account_test.go
  x/pylons/types/tx.pb.go
Labels: critical, [zube]: In Review

#1451 Cherry picked code from afti PR
  dart_sdk/lib/src/generated/pylons/execution.pb.dart
  dart_sdk/test/pylons_wallet/pylons_wallet_impl_test.dart
  wallet/lib/ipc/ipc_engine.dart
  wallet/lib/main_prod.dart
  wallet/lib/model/nft.dart
  wallet/lib/pages/home/collection_screen/collection_view_model.dart
  wallet/lib/stores/wallet_store_imp.dart
Labels: [zube]: In Progress

#1452 Collection tab w favorites folder issue#1346
  wallet/assets/images/svg/bell_icon.svg
  wallet/assets/images/svg/creations.svg
  wallet/assets/images/svg/download_easel_tooltip_bg.svg
  wallet/assets/images/svg/menu_icon.svg
  wallet/assets/images/svg/my_favorites.svg
  wallet/assets/images/svg/nft_format_3d.svg
  wallet/assets/images/svg/nft_format_audio.svg
  wallet/assets/images/svg/nft_format_image.svg
  wallet/assets/images/svg/nft_format_pdf.svg
  wallet/assets/images/svg/nft_format_video.svg
  wallet/assets/images/svg/purchases.svg
  wallet/assets/images/svg/user_avatar.svg
  wallet/i18n/de.json
  wallet/i18n/en.json
  wallet/i18n/es.json
  wallet/i18n/id.json
  wallet/i18n/ja.json
  wallet/i18n/ko.json
  wallet/i18n/ru.json
  wallet/i18n/vi.json
  wallet/lib/generated/locale_keys.g.dart
  wallet/lib/model/favorites.dart
  wallet/lib/utils/constants.dart
  wallet/lib/utils/favorites_change_notifier.dart
  wallet/lib/utils/image_util.dart
  wallet/lib/utils/svg_util.dart
Labels: [zube]: In Progress

#1463 Fix upgrade handler
  .gitignore
  .vscode/settings.json
  app/app.go
  app/upgrades/v5/upgrades.go
  scripts/run-upgrade-node.sh
  scripts/upgrade-test.sh
Labels: [zube]: In Review

#1464 Version bump to latest builds
  easel/ios/Runner.xcodeproj/project.pbxproj
  easel/lib/screens/creator_hub/creator_hub_screen.dart
  easel/lib/screens/creator_hub/widgets/delete_confirmation_dialog.dart
  easel/lib/screens/creator_hub/widgets/draft_list_tile.dart
  easel/lib/screens/creator_hub/widgets/drafts_more_bottomsheet.dart
  easel/lib/screens/creator_hub/widgets/nfts_grid_view.dart
  easel/lib/screens/creator_hub/widgets/nfts_list_tile.dart
  easel/lib/screens/creator_hub/widgets/published_nfts_bottom_sheet.dart
  easel/lib/screens/custom_widgets/initial_draft_detail_dialog.dart
  easel/lib/screens/welcome_screen/widgets/show_something_wrong_dialog.dart
  easel/lib/screens/welcome_screen/widgets/show_wallet_install_dialog.dart
  easel/lib/utils/extension_util.dart
  easel/lib/widgets/loading.dart
  easel/lib/widgets/loading_with_progress.dart
  easel/test/widget/gridview_banner_for_draft_published_test.dart
  wallet/i18n/de.json
  wallet/i18n/en.json
  wallet/i18n/es.json
  wallet/i18n/id.json
  wallet/i18n/ja.json
  wallet/i18n/ko.json
  wallet/i18n/ru.json
  wallet/i18n/vi.json
  wallet/ios/Podfile
  wallet/ios/Runner.xcodeproj/project.pbxproj
  wallet/lib/generated/locale_keys.g.dart
  wallet/lib/ipc/ipc_engine.dart
  wallet/lib/pages/home/currency_screen/model/ibc_coins.dart
  wallet/lib/pages/home/wallet_screen/add_pylon_screen.dart
  wallet/lib/pages/presenting_onboard_page/components/import_from_google_form.dart
  wallet/lib/pages/purchase_item/widgets/buy_nft_button.dart
  wallet/lib/pages/purchase_item/widgets/pay_now_dialog.dart
  wallet/lib/pages/settings/screens/general_screen/screens/payment_screen/widgets/transactions_list_view.dart
  wallet/lib/services/repository/repository.dart
  wallet/lib/stores/wallet_store_imp.dart
  wallet/lib/utils/favorites_change_notifier.dart
  wallet/pubspec.yaml
  wallet/test/mocks/mock_wallet_store.dart
Labels: [zube]: In Progress

#1490 Fix CEL execution function
  .gitignore
  x/pylons/keeper/env_collection.go
  x/pylons/types/default_cel.go
  x/pylons/types/messages_recipe_test.go
  x/pylons/types/recipe.go
  x/pylons/types/recipe_test.go
Labels: [zube]: In Review
